### ISSUE TITLE
Change default keyboard to be US English instead of UK English

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/pi-gen#14] opened 2017-01-31 19:41 UTC
[Found this in a thread about installation problems](https://www.reddit.com/r/homeassistant/comments/5r7zwb/home_assistant_is_way_harder_than_i_thought/dd5568d/). Can we change the default keyboard? Almost 40% of the current install base is in the US.

**Comment by Landrash** [comment] 2017-02-01 19:46
Should be fixed in future images since it was caused by an upstream bug in the buildscript.

**Closed by Landrash** 2017-02-01 19:46 UTC
Labels: enhancement
